version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "Installing"
  pre_build:
    commands:
      - echo "Pre-build"
      - npm install -g typescript
      - npm install
  build:
    commands:
      - echo "we are in the build block"
      - echo "we will run some tests"
      - grep -Fq "Congratulations" index.html
  post_build:
    commands:
      - echo "Post build phase"